version: '3.8'

services:
  observer:
    build:
      context: .
      dockerfile: Dockerfile.observer
    container_name: tracr-observer
    volumes:
      - ./src:/app/src
    ports:
      - "9000:9000"
    networks:
      - tracr_network

  participant:
    build:
      context: .
      dockerfile: Dockerfile.participant
    container_name: tracr-participant
    volumes:
      - ./src:/app/src
    ports:
      - "22"
    networks:
      - tracr_network
    deploy:
      replicas: 2

networks:
  tracr_network:
    driver: bridge