# config/alexnetsplit.yaml

# DEFAULT CONFIGURATIONS
default:
  device: cuda
  font_path: config/fonts/DejaVuSans-Bold.ttf

# LOGGING CONFIGURATIONS
logging:
  log_level: INFO
  log_file: logs/app.log
  progress_interval: 10  
  layer_progress: true
  image_progress: true  
  save_images: true     
  detailed_timing: true 

# MODEL CONFIGURATIONS
model:
  model_name: alexnet
  version: null
  pretrained: true
  weight_path: null
  input_size: [3, 224, 224]
  hook_style: pre
  split_layer: 5
  save_layers: [2, 4, 6]
  total_layers: 8
  num_classes: null
  mode: eval
  depth: 2
  flush_buffer_size: 100
  warmup_iterations: 10
  log_file: logs/alexnetsplit.log

# DATASET CONFIGURATIONS
dataset:
  module: imagenet
  class: ImageNetDataset
  task: classification
  args:
    root: data/imagenet
    class_names: data/imagenet/imagenet_classes.txt
    img_directory: data/imagenet/sample_images
    transform: null
    max_samples: -1

# DATALOADER CONFIGURATIONS
dataloader:
  batch_size: 1
  shuffle: false
  num_workers: 4
  collate_fn: custom_image_collate

# EXPERIMENT CONFIGURATIONS
compression:
  clevel: 3
  filter: SHUFFLE
  codec: ZSTD
