# DEVICE CONFIGURATION TEMPLATE

# Rename this file to devices_config.yaml after you have set up the SSH keys and tested connectivity.

# This file defines the network configuration for split inference experiments.
# It requires proper setup of SSH keys and network connectivity between devices.

# NETWORK SETUP CHECKLIST:
# 1. Ensure all devices are on the same network
# 2. Configure SSH keys between devices
# 3. Test connectivity before running experiments

# DEVICE TYPES:
# - SERVER: The main device that coordinates the split inference (typically more powerful)
# - PARTICIPANT: Edge devices that participate in the split inference (e.g., NVIDIA Jetson, Raspberry Pi)

# FINDING DEVICE IP ADDRESSES:
# Linux/WSL: hostname -I | awk '{print $1}'
# Windows: ipconfig
# Note: IP addresses must be on the same subnet for devices to communicate

# SSH KEY SETUP:
# 1. Generate SSH key pair on source device:
#    ssh-keygen -t rsa -b 4096 -f ~/.ssh/device_name_key
# 2. Copy public key to destination device:
#    ssh-copy-id -i ~/.ssh/device_name_key.pub user@device_ip
# 3. Place private keys in config/pkeys/ directory
# 4. Test connection: ssh -i ~/.ssh/device_name_key user@device_ip

# TROUBLESHOOTING:
# 1. Connection issues:
#    - Verify IP addresses are correct and devices are on same network
#    - Check SSH key permissions (should be 600)
#    - Ensure private keys are in config/pkeys/ directory
#    - Test SSH connection manually first

devices:
  - device_type: SERVER                 # Main computing device
    connection_params:
      - host: <server_ip_address>       # e.g., 192.168.1.100
        user: <username>                # SSH username
        pkey_fp: <server_key.rsa>       # Private key filename in config/pkeys/
        default: true                   # Primary connection parameters

  - device_type: PARTICIPANT            # Edge device
    connection_params:
      - host: <participant_ip_address>  # e.g., 192.168.1.101
        user: <username>                # SSH username
        pkey_fp: <participant_key.rsa>  # Private key filename in config/pkeys/
        default: true                   # Primary connection parameters


# SPLIT INFERENCE NETWORK CONFIGURATIONS
# Defines the roles of devices in the split inference setup
split_inference_network:
  server: SERVER           # Must match device_type above
  participants:
    - PARTICIPANT          # Must match device_type above

