# This file is used to store information about the devices that have been configured for use with experiments. Each device has:
#   1. a unique nickname (the top-level keys in this file)
#   2. one of the supported device types
#   3. a list of connection parameters, each of which has:
#       a. a hostname or IP address (host)
#       b. a username (user)
#       c. a path to a private key file (pkey_fp)
#       d. a boolean indicating whether this is the default connection parameter for this device (default)
#
#
# STEPS TO CONNECT TO DEVICES:
# 1. Find IP address of current device (localhost):
#    hostname -I | awk '{print $1}'
# 2. Connect Edge device (Jetson) via USB serial:
#    - Connect Edge device to Laptop via USB cable
#    - On Laptop, Device Manager / Ports (COM & LPT) / COM#
#    - PuTTy connect via Serial -> Speed = 115200
#    - Authenticate and connect to Edge device
# 3. Find IP address of Edge device:
#    - hostname -I | awk '{print $1}'
# 4. Turn on WiFi on Edge device:
#    - nmcli r wifi on
# 5. List WiFi networks:
#    - nmcli d wifi list     # SSID is the WiFi name
# 6. Connect to Edge device WiFi:
#    - sudo nmcli dev wifi con "SSID" password "WiFiPassword"
# 7. SSH into Edge device:
#    - ssh <edge_device_username>@<edge_device_ip_address>
#
# Once you are connected to the Edge device via usb serial, you can create a ssh-keypair on your laptop
# and the Edge device and share the public key with the other party (inside ~/.ssh/authorized_keys)
#
# The top-level names (localhost, <edge_device_username>) need to match exactly as defined in alexnetsplit.yaml
#
# The rpyc service is a system-wide service that is used to control the RPyC server.
# It is located at /usr/local/bin/rpyc_service.py
# To create a system-wide service, run the following command:
#   - sudo cp rpyc_service.py /usr/local/bin/rpyc.service
#   - sudo systemctl enable rpyc.service
#   - sudo systemctl start rpyc.service
#
# To check the status of the rpyc service, run the following command:
#   - sudo systemctl status rpyc.service
#
# If it is not already running, start the rpyc service with the following command:
#   - sudo systemctl start rpyc.service
# Notice you that you've to configure ssh for passwordless `sudo` execution as root.
#
# To configure ssh for passwordless `sudo` execution as root, run the following command:
# Open the sudoers file in a text editor:
#   - sudo visudo
# Add the following line to the end of the file:
# # Allow '<localhost_username>' to run specific systemctl commands without a password on WSL
# <localhost_username> ALL=(ALL) NOPASSWD: /bin/systemctl start rpyc_wsl.service
# # Allow '<edge_device_username>' to run specific systemctl commands without a password on Edge device
# <edge_device_username> ALL=(ALL) NOPASSWD: /bin/systemctl start rpyc.service
#
# Verify sudoers configuration:
# # On WSL
# sudo -l -U <localhost_username>
#
# # On Edge device
# sudo -l -U <edge_device_username>

devices:
  - device_type: SERVER
    connection_params:
      - host: <server_ip_address>
        user: <username>
        pkey_fp: <path_to_pkey> # put inside config/pkeys/
        default: true

  - device_type: PARTICIPANT
    connection_params:
      - host: <participant_ip_address>
        user: <username>
        pkey_fp: <path_to_pkey> # put inside config/pkeys/
        default: true

# SPLIT INFERENCE NETWORK CONFIGURATIONS
split_inference_network:
  server: SERVER
  participants:
    - PARTICIPANT

