# config/modelsplit_template.yaml

# Update this template with the appropriate configurations for your model split inference experiment

# MODEL SPLIT CONFIGURATION TEMPLATE
# ---------------------------------
# This template defines the configuration for split inference experiments.
# Rename this file to match your model (e.g., alexnetsplit.yaml, yolosplit.yaml)

# DEFAULT CONFIGURATIONS
# ---------------------
default:
  device: cuda                   # Options: 'cuda' (GPU), 'cpu' (CPU). Default is cuda.
  font_path: <font_path>         # Path to font file for visualization; e.g., fonts/DejaVuSans-Bold.ttf.
  log_level: INFO                # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL. Default is INFO.
  log_file: <log_file>           # Central log file for application-wide logging. Default is logs/app.log

# MODEL CONFIGURATIONS
# -------------------
model:
  model_name: null               # REQUIRED: Model architecture name (e.g., 'alexnet', 'yolov8s')
  version: null                  # Model version if applicable. Default is null.
  pretrained: false              # Whether to use pretrained weights. Default is false.
  weight_path: null              # Path to custom weights file; e.g., 'path/to/weights/best.pt' for YOLOv8. Default is null.
  input_size: [3, 224, 224]      # REQUIRED: Input tensor dimensions [channels, height, width]. Common sizes: [3, 224, 224] for AlexNet, [3, 640, 640] for YOLOv8.
  hook_style: pre                # Where to insert hooks in model layers. Options: 'pre' (before layer execution), 'post' (after layer execution).
  split_layer: null              # REQUIRED: Layer index where model will be split. Note: Must be less than total_layers.
  save_layers: [2, 4, 6]         # Layer indices to save intermediate outputs. Useful for debugging and visualization.
  total_layers: null             # REQUIRED: Total number of layers in model. Example: 8 for AlexNet, 23 for YOLOv8.
  num_classes: null              # Number of output classes. null: Use model's default. Example: 1000 for ImageNet, 2 for binary classification.
  mode: eval                     # Model operation mode. Options: 'eval' (recommended for split inference), 'train'.
  depth: 2                       # Depth for recursive model layer exploration. Default is 2.
  flush_buffer_size: 100         # Number of inferences before results storage. Default is 100.
  warmup_iterations: 10          # Iterations to stabilize performance metrics. Default is 10.
  log_file: logs/modelsplit.log  # Separate log file for model operations. Rename to match your model (e.g., alexnetsplit.log).

# DATASET CONFIGURATIONS
# ---------------------
dataset:
  module: null                  # REQUIRED: Python module name for dataset. Examples: 'imagenet', 'onion'. Defined in src/experiment_design/datasets/
  class: null                   # REQUIRED: Dataset class name. Examples: 'ImageNetDataset', 'OnionDataset'.
  args:
    root: null                  # REQUIRED: Dataset root directory. Example: 'data/imagenet', 'data/onion'.
    class_names: null           # Class names or path to class names file. Examples: 'data/imagenet/imagenet_classes.txt', ["with_weeds", "without_weeds"].
    img_directory: null         # Directory containing images. Example: 'data/imagenet/sample_images'.
    transform: null             # Custom transformations. null: Use default transforms for the model.
    max_samples: -1             # Maximum number of samples to process. -1: Process all available samples.

# DATALOADER CONFIGURATIONS
# ------------------------
dataloader:
  batch_size: 1                 # Number of samples per batch. Recommended: 1 for split inference.
  shuffle: false                # Whether to shuffle the dataset. Recommended: false for consistent results.
  num_workers: 4                # Number of parallel data loading workers. Adjust based on CPU cores available.
  collate_fn: null              # Custom batch collation function. null: Use default collation.


# # EXAMPLE CONFIGURATION
# # ----------------------
# # DEFAULT CONFIGURATIONS
# default:
#   device: cuda
#   font_path: fonts/DejaVuSans-Bold.ttf
#   log_level: INFO
#   log_file: logs/app.log

# # MODEL CONFIGURATIONS
# model:
#   model_name: yolov8s
#   version: null
#   pretrained: false
#   weight_path: data/onion/weights/best.pt
#   input_size: [3, 224, 224]
#   hook_style: post
#   split_layer: 10
#   save_layers: [2, 4, 6]
#   total_layers: 23
#   num_classes: null
#   mode: eval
#   depth: 2
#   flush_buffer_size: 100
#   warmup_iterations: 10
#   log_file: logs/yolosplit.log

# # DATASET CONFIGURATIONS
# dataset:
#   module: onion
#   class: OnionDataset
#   args:
#     root: data/onion
#     class_names: ["with_weeds", "without_weeds"]
#     img_directory: data/onion/testing
#     transform: null
#     max_samples: -1

# # DATALOADER CONFIGURATIONS
# dataloader:
#   batch_size: 1
#   shuffle: false
#   num_workers: 4
#   collate_fn: null
