# config/alexnetsplit.yaml
# This configuration file defines a split inference setup for the AlexNet model

participant_types:
  # Server configuration
  server:
    service:
      module: split_inference
      class: ServerService
    model:
      model_name: alexnet
      device: cpu
      mode: eval
      depth: np.inf
      input_size: [3, 224, 224]
      class: default

  # Participant configuration
  participant:
    service:
      module: split_inference
      class: ParticipantService
    model:
      model_name: alexnet
      device: cpu
      mode: eval
      depth: np.inf
      input_size: [3, 224, 224]
      class: default

# Map participant types to specific devices and assign unique names
participant_instances:
  - device: localhost_wsl
    node_type: server
    instance_name: SERVER
  - device: racr
    node_type: participant
    instance_name: PARTICIPANT

# Define initial tasks for each participant to start the experiment
playbook:
  SERVER:
    - task_type: infer_over_dataset_task
      params:
        dataset_module: imagenet
        dataset_instance: imagenet10_tr
    - task_type: finish_signal_task

  PARTICIPANT:
    - task_type: wait_for_tasks_task
      params:
        task_type_to_wait_for: infer_over_dataset_task
